namespace MetaLinkCompatTool;

public enum AppLanguage
{
    ZhCn,
    JaJp,
    EnUs
}

public sealed record LanguageOption(AppLanguage Language, string DisplayName)
{
    public override string ToString() => DisplayName;
}

public static class I18n
{
    public static readonly LanguageOption[] Options =
    [
        new(AppLanguage.ZhCn, "中文"),
        new(AppLanguage.JaJp, "日本語"),
        new(AppLanguage.EnUs, "English")
    ];

    private static readonly Dictionary<AppLanguage, Dictionary<string, string>> Strings = new()
    {
        [AppLanguage.EnUs] = new()
        {
            ["AppTitle"] = "Meta Link Compatibility Tool",
            ["Subtitle"] = "Patch local compatibility lists, manage highwind, and recover with backups.",
            ["Admin"] = "Administrator mode",
            ["Standard"] = "Standard user mode",
            ["Refresh"] = "Refresh",
            ["Language"] = "Language",
            ["DetectedHardware"] = "Detected hardware",
            ["Cpu"] = "CPU",
            ["GpuSelect"] = "GPU to add to Meta compatibility list",
            ["CompatibilityStatus"] = "Compatibility and encoder status",
            ["Actions"] = "Actions",
            ["Backups"] = "Backups",
            ["Log"] = "Log",
            ["ApplyPatch"] = "Apply patch",
            ["Rollback"] = "Rollback selected",
            ["KillMeta"] = "Kill Meta services",
            ["RestartMeta"] = "Restart Meta services",
            ["StartHighwind"] = "Start highwind",
            ["LaunchClient"] = "Launch Meta client",
            ["InstallAutostart"] = "Install autostart",
            ["RemoveAutostart"] = "Remove autostart",
            ["SetEncoder"] = "Set HEVC defaults",
            ["OpenFeedback"] = "Open feedback TXT",
            ["OpenBackups"] = "Open backups folder",
            ["LockLocal"] = "Mark local Compatibility.json read-only",
            ["EncoderDefaults"] = "Also set HEVC encoder defaults",
            ["BackupHint"] = "Every Apply operation snapshots both Compatibility.json files and HKCU Oculus RemoteHeadset settings before writing.",
            ["NotLoaded"] = "Not loaded",
            ["NoGpu"] = "No GPU selected.",
            ["Unknown"] = "unknown",
            ["Vendor"] = "Vendor",
            ["Pid"] = "PID",
            ["Driver"] = "Driver",
            ["Vram"] = "VRAM reported by WMI",
            ["CompatFiles"] = "Compatibility files",
            ["Encoder"] = "Encoder",
            ["Exists"] = "Exists",
            ["ReadOnly"] = "ReadOnly",
            ["LastWrite"] = "LastWrite",
            ["Whitelist"] = "WhiteList",
            ["MinSpec"] = "MinSpec",
            ["StatusRefreshed"] = "Status refreshed.",
            ["RefreshFailed"] = "Refresh failed",
            ["NoHardware"] = "No hardware",
            ["RefreshHardwareFirst"] = "Refresh hardware first.",
            ["AdminRequired"] = "Administrator required",
            ["RelaunchAsAdmin"] = "Relaunch this tool as administrator now?",
            ["NeedAdminWrite"] = "Writing Program Files compatibility data usually requires administrator rights.",
            ["NeedAdminRollback"] = "Rollback writes compatibility files back to Meta folders.",
            ["NeedAdminStop"] = "Stopping OVRService requires administrator rights.",
            ["NeedAdminRestart"] = "Restarting OVRService requires administrator rights.",
            ["NoBackup"] = "No backup selected.",
            ["ApplyStarted"] = "Apply patch started.",
            ["ApplyDone"] = "Apply patch completed.",
            ["RollbackStarted"] = "Rollback started.",
            ["RollbackDone"] = "Rollback completed.",
            ["KillStarted"] = "Kill Meta services started.",
            ["KillDone"] = "Meta services and related processes stopped where possible.",
            ["RestartStarted"] = "Restart Meta services started.",
            ["RestartDone"] = "Meta runtime restarted and highwind_service checked.",
            ["HighwindStarted"] = "highwind_service started or already running.",
            ["ClientLaunch"] = "Meta client launch requested.",
            ["AutostartInstalled"] = "Installed current-user highwind autostart.",
            ["AutostartRemoved"] = "Removed current-user highwind autostart.",
            ["EncoderSet"] = "Set HEVC=1, BitrateMbps=0, EncodeWidth=0, DBR=0.",
            ["BackupCreated"] = "Backup created",
            ["HighwindChecked"] = "highwind_service checked.",
            ["RestoredBackup"] = "Restored backup",
            ["OpenPath"] = "Open path",
            ["PathNotFound"] = "Path not found"
        },
        [AppLanguage.ZhCn] = new()
        {
            ["AppTitle"] = "Meta Link 兼容性工具",
            ["Subtitle"] = "写入本地兼容列表、管理 highwind，并通过备份回滚。",
            ["Admin"] = "管理员模式",
            ["Standard"] = "标准用户模式",
            ["Refresh"] = "刷新",
            ["Language"] = "语言",
            ["DetectedHardware"] = "检测到的硬件",
            ["Cpu"] = "CPU",
            ["GpuSelect"] = "要写入 Meta 兼容列表的 GPU",
            ["CompatibilityStatus"] = "兼容性与编码器状态",
            ["Actions"] = "操作",
            ["Backups"] = "备份",
            ["Log"] = "日志",
            ["ApplyPatch"] = "写入补丁",
            ["Rollback"] = "回滚所选备份",
            ["KillMeta"] = "结束 Meta 服务",
            ["RestartMeta"] = "重启 Meta 服务",
            ["StartHighwind"] = "启动 highwind",
            ["LaunchClient"] = "启动 Meta 客户端",
            ["InstallAutostart"] = "安装自启动",
            ["RemoveAutostart"] = "移除自启动",
            ["SetEncoder"] = "设置 HEVC 默认值",
            ["OpenFeedback"] = "打开反馈 TXT",
            ["OpenBackups"] = "打开备份文件夹",
            ["LockLocal"] = "将本地 Compatibility.json 标记为只读",
            ["EncoderDefaults"] = "同时设置 HEVC 编码默认值",
            ["BackupHint"] = "每次写入前都会备份两个 Compatibility.json 和 HKCU Oculus RemoteHeadset 设置。",
            ["NotLoaded"] = "尚未加载",
            ["NoGpu"] = "未选择 GPU。",
            ["Unknown"] = "未知",
            ["Vendor"] = "厂商",
            ["Pid"] = "PID",
            ["Driver"] = "驱动",
            ["Vram"] = "WMI 报告的显存",
            ["CompatFiles"] = "兼容性文件",
            ["Encoder"] = "编码器",
            ["Exists"] = "存在",
            ["ReadOnly"] = "只读",
            ["LastWrite"] = "最后写入",
            ["Whitelist"] = "白名单",
            ["MinSpec"] = "最低规格",
            ["StatusRefreshed"] = "状态已刷新。",
            ["RefreshFailed"] = "刷新失败",
            ["NoHardware"] = "没有硬件信息",
            ["RefreshHardwareFirst"] = "请先刷新硬件信息。",
            ["AdminRequired"] = "需要管理员权限",
            ["RelaunchAsAdmin"] = "是否立即以管理员身份重新启动此工具？",
            ["NeedAdminWrite"] = "写入 Program Files 内的兼容性数据通常需要管理员权限。",
            ["NeedAdminRollback"] = "回滚需要写回 Meta 文件夹中的兼容性文件。",
            ["NeedAdminStop"] = "停止 OVRService 需要管理员权限。",
            ["NeedAdminRestart"] = "重启 OVRService 需要管理员权限。",
            ["NoBackup"] = "未选择备份。",
            ["ApplyStarted"] = "开始写入补丁。",
            ["ApplyDone"] = "补丁写入完成。",
            ["RollbackStarted"] = "开始回滚。",
            ["RollbackDone"] = "回滚完成。",
            ["KillStarted"] = "开始结束 Meta 服务。",
            ["KillDone"] = "已尽可能停止 Meta 服务和相关进程。",
            ["RestartStarted"] = "开始重启 Meta 服务。",
            ["RestartDone"] = "Meta Runtime 已重启，并已检查 highwind_service。",
            ["HighwindStarted"] = "highwind_service 已启动或已在运行。",
            ["ClientLaunch"] = "已请求启动 Meta 客户端。",
            ["AutostartInstalled"] = "已安装当前用户 highwind 自启动。",
            ["AutostartRemoved"] = "已移除当前用户 highwind 自启动。",
            ["EncoderSet"] = "已设置 HEVC=1、BitrateMbps=0、EncodeWidth=0、DBR=0。",
            ["BackupCreated"] = "已创建备份",
            ["HighwindChecked"] = "已检查 highwind_service。",
            ["RestoredBackup"] = "已恢复备份",
            ["OpenPath"] = "打开路径",
            ["PathNotFound"] = "路径不存在"
        },
        [AppLanguage.JaJp] = new()
        {
            ["AppTitle"] = "Meta Link 互換性ツール",
            ["Subtitle"] = "ローカル互換リストの更新、highwind 管理、バックアップからの復元を行います。",
            ["Admin"] = "管理者モード",
            ["Standard"] = "標準ユーザーモード",
            ["Refresh"] = "更新",
            ["Language"] = "言語",
            ["DetectedHardware"] = "検出されたハードウェア",
            ["Cpu"] = "CPU",
            ["GpuSelect"] = "Meta 互換リストへ追加する GPU",
            ["CompatibilityStatus"] = "互換性とエンコーダー状態",
            ["Actions"] = "操作",
            ["Backups"] = "バックアップ",
            ["Log"] = "ログ",
            ["ApplyPatch"] = "パッチ適用",
            ["Rollback"] = "選択バックアップを復元",
            ["KillMeta"] = "Meta サービス停止",
            ["RestartMeta"] = "Meta サービス再起動",
            ["StartHighwind"] = "highwind 起動",
            ["LaunchClient"] = "Meta クライアント起動",
            ["InstallAutostart"] = "自動起動を追加",
            ["RemoveAutostart"] = "自動起動を削除",
            ["SetEncoder"] = "HEVC 既定値を設定",
            ["OpenFeedback"] = "フィードバック TXT",
            ["OpenBackups"] = "バックアップフォルダー",
            ["LockLocal"] = "ローカル Compatibility.json を読み取り専用にする",
            ["EncoderDefaults"] = "HEVC エンコーダー既定値も設定する",
            ["BackupHint"] = "適用前に 2 つの Compatibility.json と HKCU Oculus RemoteHeadset 設定をバックアップします。",
            ["NotLoaded"] = "未読み込み",
            ["NoGpu"] = "GPU が選択されていません。",
            ["Unknown"] = "不明",
            ["Vendor"] = "ベンダー",
            ["Pid"] = "PID",
            ["Driver"] = "ドライバー",
            ["Vram"] = "WMI 報告 VRAM",
            ["CompatFiles"] = "互換性ファイル",
            ["Encoder"] = "エンコーダー",
            ["Exists"] = "存在",
            ["ReadOnly"] = "読み取り専用",
            ["LastWrite"] = "最終更新",
            ["Whitelist"] = "ホワイトリスト",
            ["MinSpec"] = "最小仕様",
            ["StatusRefreshed"] = "状態を更新しました。",
            ["RefreshFailed"] = "更新に失敗しました",
            ["NoHardware"] = "ハードウェア情報なし",
            ["RefreshHardwareFirst"] = "先にハードウェア情報を更新してください。",
            ["AdminRequired"] = "管理者権限が必要です",
            ["RelaunchAsAdmin"] = "管理者として再起動しますか？",
            ["NeedAdminWrite"] = "Program Files 内の互換性データを書き込むには通常、管理者権限が必要です。",
            ["NeedAdminRollback"] = "復元では Meta フォルダー内の互換性ファイルを書き戻します。",
            ["NeedAdminStop"] = "OVRService の停止には管理者権限が必要です。",
            ["NeedAdminRestart"] = "OVRService の再起動には管理者権限が必要です。",
            ["NoBackup"] = "バックアップが選択されていません。",
            ["ApplyStarted"] = "パッチ適用を開始しました。",
            ["ApplyDone"] = "パッチ適用が完了しました。",
            ["RollbackStarted"] = "復元を開始しました。",
            ["RollbackDone"] = "復元が完了しました。",
            ["KillStarted"] = "Meta サービス停止を開始しました。",
            ["KillDone"] = "Meta サービスと関連プロセスを可能な限り停止しました。",
            ["RestartStarted"] = "Meta サービス再起動を開始しました。",
            ["RestartDone"] = "Meta Runtime を再起動し、highwind_service を確認しました。",
            ["HighwindStarted"] = "highwind_service は起動済み、または既に実行中です。",
            ["ClientLaunch"] = "Meta クライアントの起動を要求しました。",
            ["AutostartInstalled"] = "現在のユーザーに highwind 自動起動を追加しました。",
            ["AutostartRemoved"] = "現在のユーザーの highwind 自動起動を削除しました。",
            ["EncoderSet"] = "HEVC=1、BitrateMbps=0、EncodeWidth=0、DBR=0 を設定しました。",
            ["BackupCreated"] = "バックアップを作成しました",
            ["HighwindChecked"] = "highwind_service を確認しました。",
            ["RestoredBackup"] = "バックアップを復元しました",
            ["OpenPath"] = "パスを開く",
            ["PathNotFound"] = "パスが見つかりません"
        }
    };

    public static string T(AppLanguage language, string key)
    {
        if (Strings.TryGetValue(language, out var table) && table.TryGetValue(key, out var value))
        {
            return value;
        }

        return Strings[AppLanguage.EnUs].TryGetValue(key, out var fallback) ? fallback : key;
    }
}
